[[battery_cli]]
arch = "aarch64"
git-tree-sha1 = "324ac944553cfb8201cba83b2028874e21ea1b17"
os = "macos"

    [[battery_cli.download]]
    sha256 = "b391dc787556ea6e8d823a02e4e70353cc120bd4f38ce6ceea69e3e1ce1a9dce"
    url = "https://github.com/JuliaBinaryWrappers/battery_cli_jll.jl/releases/download/battery_cli-v0.11.0+0/battery_cli.v0.11.0.aarch64-apple-darwin.tar.gz"
[[battery_cli]]
arch = "aarch64"
git-tree-sha1 = "10684b16e67d5376085c5622bcd506052a3d1a38"
libc = "glibc"
os = "linux"

    [[battery_cli.download]]
    sha256 = "712adda3877471f52781effc80ff5028c1274af21bf20ce1f1e7e54ef924d736"
    url = "https://github.com/JuliaBinaryWrappers/battery_cli_jll.jl/releases/download/battery_cli-v0.11.0+0/battery_cli.v0.11.0.aarch64-linux-gnu.tar.gz"
[[battery_cli]]
arch = "aarch64"
git-tree-sha1 = "10684b16e67d5376085c5622bcd506052a3d1a38"
libc = "musl"
os = "linux"

    [[battery_cli.download]]
    sha256 = "712adda3877471f52781effc80ff5028c1274af21bf20ce1f1e7e54ef924d736"
    url = "https://github.com/JuliaBinaryWrappers/battery_cli_jll.jl/releases/download/battery_cli-v0.11.0+0/battery_cli.v0.11.0.aarch64-linux-musl.tar.gz"
[[battery_cli]]
arch = "aarch64"
git-tree-sha1 = "4eb9687894c5701540748dc66bfa78e4db7e3350"
os = "freebsd"

    [[battery_cli.download]]
    sha256 = "21769a7c7aeb643d5631f44709f21888e2f935f3c130b221d8e5a952333a6863"
    url = "https://github.com/JuliaBinaryWrappers/battery_cli_jll.jl/releases/download/battery_cli-v0.11.0+0/battery_cli.v0.11.0.aarch64-unknown-freebsd.tar.gz"
[[battery_cli]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5d8d7971b26cead405d5010e4b5b5f27c98b1841"
libc = "glibc"
os = "linux"

    [[battery_cli.download]]
    sha256 = "db7b695164c0d6b31b83126f5a09c4f95d904e7adbf212ad1d9ea282ed7ccad1"
    url = "https://github.com/JuliaBinaryWrappers/battery_cli_jll.jl/releases/download/battery_cli-v0.11.0+0/battery_cli.v0.11.0.armv6l-linux-gnueabihf.tar.gz"
[[battery_cli]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5d8d7971b26cead405d5010e4b5b5f27c98b1841"
libc = "musl"
os = "linux"

    [[battery_cli.download]]
    sha256 = "db7b695164c0d6b31b83126f5a09c4f95d904e7adbf212ad1d9ea282ed7ccad1"
    url = "https://github.com/JuliaBinaryWrappers/battery_cli_jll.jl/releases/download/battery_cli-v0.11.0+0/battery_cli.v0.11.0.armv6l-linux-musleabihf.tar.gz"
[[battery_cli]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "97732974fe04a30f5f40bf8bed6652969cc66801"
libc = "glibc"
os = "linux"

    [[battery_cli.download]]
    sha256 = "29250ce8386a104776298fccbad3a28a9c929a87db5b392b12af7f44d670ad7e"
    url = "https://github.com/JuliaBinaryWrappers/battery_cli_jll.jl/releases/download/battery_cli-v0.11.0+0/battery_cli.v0.11.0.armv7l-linux-gnueabihf.tar.gz"
[[battery_cli]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "97732974fe04a30f5f40bf8bed6652969cc66801"
libc = "musl"
os = "linux"

    [[battery_cli.download]]
    sha256 = "29250ce8386a104776298fccbad3a28a9c929a87db5b392b12af7f44d670ad7e"
    url = "https://github.com/JuliaBinaryWrappers/battery_cli_jll.jl/releases/download/battery_cli-v0.11.0+0/battery_cli.v0.11.0.armv7l-linux-musleabihf.tar.gz"
[[battery_cli]]
arch = "i686"
git-tree-sha1 = "df8e51e445608d9c4722ed72ac5444b0491fa39c"
libc = "glibc"
os = "linux"

    [[battery_cli.download]]
    sha256 = "9483a999317530de950c1e2cd079bf9c2a06f1b428e433dee022a5493af7e858"
    url = "https://github.com/JuliaBinaryWrappers/battery_cli_jll.jl/releases/download/battery_cli-v0.11.0+0/battery_cli.v0.11.0.i686-linux-gnu.tar.gz"
[[battery_cli]]
arch = "i686"
git-tree-sha1 = "df8e51e445608d9c4722ed72ac5444b0491fa39c"
libc = "musl"
os = "linux"

    [[battery_cli.download]]
    sha256 = "9483a999317530de950c1e2cd079bf9c2a06f1b428e433dee022a5493af7e858"
    url = "https://github.com/JuliaBinaryWrappers/battery_cli_jll.jl/releases/download/battery_cli-v0.11.0+0/battery_cli.v0.11.0.i686-linux-musl.tar.gz"
[[battery_cli]]
arch = "i686"
git-tree-sha1 = "e1a2280f0fe8d0f068231eea017ea4cc94dac5fd"
os = "windows"

    [[battery_cli.download]]
    sha256 = "e9fc120eacb18915ac74b92726cdc41a5ddc505e99a662cc4fd033b94e983196"
    url = "https://github.com/JuliaBinaryWrappers/battery_cli_jll.jl/releases/download/battery_cli-v0.11.0+0/battery_cli.v0.11.0.i686-w64-mingw32.tar.gz"
[[battery_cli]]
arch = "powerpc64le"
git-tree-sha1 = "ad6f7bf4bbf6f60dcb4d086eee771c33f2f8fa53"
libc = "glibc"
os = "linux"

    [[battery_cli.download]]
    sha256 = "bed2c297a2b78e7f803d511831488571e8c2f20f2bf76c748da4f8d51d833081"
    url = "https://github.com/JuliaBinaryWrappers/battery_cli_jll.jl/releases/download/battery_cli-v0.11.0+0/battery_cli.v0.11.0.powerpc64le-linux-gnu.tar.gz"
[[battery_cli]]
arch = "x86_64"
git-tree-sha1 = "38dbf49412ff1079cf00a90ad6efbc5bdd83e361"
os = "macos"

    [[battery_cli.download]]
    sha256 = "e2d6d4ea6b114448d02c58cb264584be9d94e3b883f57678be32dfdfd490cdb6"
    url = "https://github.com/JuliaBinaryWrappers/battery_cli_jll.jl/releases/download/battery_cli-v0.11.0+0/battery_cli.v0.11.0.x86_64-apple-darwin.tar.gz"
[[battery_cli]]
arch = "x86_64"
git-tree-sha1 = "7a97303905bbb99501af73e17a3c7422c9fb5202"
libc = "glibc"
os = "linux"

    [[battery_cli.download]]
    sha256 = "18999af22cb805f2c4fea034effae25f4405a80b50b17682958a01b00556e35d"
    url = "https://github.com/JuliaBinaryWrappers/battery_cli_jll.jl/releases/download/battery_cli-v0.11.0+0/battery_cli.v0.11.0.x86_64-linux-gnu.tar.gz"
[[battery_cli]]
arch = "x86_64"
git-tree-sha1 = "7a97303905bbb99501af73e17a3c7422c9fb5202"
libc = "musl"
os = "linux"

    [[battery_cli.download]]
    sha256 = "18999af22cb805f2c4fea034effae25f4405a80b50b17682958a01b00556e35d"
    url = "https://github.com/JuliaBinaryWrappers/battery_cli_jll.jl/releases/download/battery_cli-v0.11.0+0/battery_cli.v0.11.0.x86_64-linux-musl.tar.gz"
[[battery_cli]]
arch = "x86_64"
git-tree-sha1 = "870bdc32d648cdadabd7116316b10c21c8a90fe2"
os = "freebsd"

    [[battery_cli.download]]
    sha256 = "6b30f0f1ca607e3f13cb970dc48fe613f75ba42151cde980b7bddff1f776f7a8"
    url = "https://github.com/JuliaBinaryWrappers/battery_cli_jll.jl/releases/download/battery_cli-v0.11.0+0/battery_cli.v0.11.0.x86_64-unknown-freebsd.tar.gz"
[[battery_cli]]
arch = "x86_64"
git-tree-sha1 = "008b2cf822b5e39281fa492722cb76d7f149e88d"
os = "windows"

    [[battery_cli.download]]
    sha256 = "737534729bb22846e154a278e0e72c62b05a0b4e640e5adeff3d367574e6feec"
    url = "https://github.com/JuliaBinaryWrappers/battery_cli_jll.jl/releases/download/battery_cli-v0.11.0+0/battery_cli.v0.11.0.x86_64-w64-mingw32.tar.gz"
