# Autogenerated wrapper script for battery_cli_jll for x86_64-w64-mingw32
export battery

JLLWrappers.@generate_wrapper_header("battery_cli")
JLLWrappers.@declare_executable_product(battery)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        battery,
        "bin\\battery.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
